apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod1
  labels:
    app: nginx
spec:
  containers:
  - name: nginx1
    image: nginx
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  labels:
    app: nginx
spec:
  containers:
  - name: nginx2
    image: nginx
